#!/usr/bin/env python3

import random, threading, time

def generate_boggle_board(dice):
    random.shuffle(dice)
    board = [random.choice(die) for die in dice]
    return [board[i:i+4] for i in range(0, 16, 4)]

def print_board(board):
    for row in board:
        formatted_row = ['Qu' if letter == 'Q' else letter + ' ' for letter in row]
        print(' '.join(formatted_row))

def start_timer(duration):
    time.sleep(duration)
    print("\033[91mTIME UP\033[0m")  # 91 is the ANSI code for bright red

def main():
    dice = [
        "AAEEGN", "ELRTTY", "AOOTTW", "ABBJOO",
        "EHRTVW", "CIMOTU", "DISTTY", "EIOSST",
        "DELRVY", "ACHOPS", "HIMNQU", "EEINSU",
        "EEGHNW", "AFFKPS", "HLNNRZ", "DEILRX"
    ]

    board = generate_boggle_board(dice)
    print_board(board)

    timer_thread = threading.Thread(target=start_timer, args=(180,))
    timer_thread.start()

if __name__ == "__main__":
    main()
